export const VALIDATE_LOGIN = "VALIDATE_LOGIN";
export const VALIDATE_LOGIN_ASYNC = "VALIDATE_LOGIN_ASYNC";
export const VALIDATE_LOGIN_ASYNC_ERROR = "VALIDATE_LOGIN_ASYNC_ERROR";

export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
export const FETCH_USER_BY_ID_ASYNC = "FETCH_USER_BY_ID_ASYNC";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_ASYNC = "ADD_PRODUCT_ASYNC";